language: ruby
cache: bundler
dist: trusty
sudo: required
rvm:
  - 2.6.3
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # prevents nokogiri from downloading slooooow libraries
before_install:
    - gem update --system
    - gem install bundler
before_script:
  - bundle exec rake db:migrate
addons:
  chrome: stable
  postgresql: "9.4"
services:
  - postgresql
script: "bundle exec rspec spec/"
before_script:
  - psql -c 'create database can_you_donate_test;' -U postgres
  - sleep 3
