default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  database: can_you_donate_development

test:
  <<: *default
  database: can_you_donate_test

production: &deploy
  encoding: utf8
  min_messages: warning
  pool: <%= [Integer(ENV.fetch('MAX_THREADS', 5)), Integer(ENV.fetch('DB_POOL', 5))].max %>
  timeout: 5000
  url:  <%= ENV.fetch('DATABASE_URL', '') %>
